### ISSUE TITLE
React 0.14 Compatibility

### ISSUE THREAD

**Issue by jonjaques** [vaiRk/responsive-fixed-data-table#7]
Looks like this module is requiring `react/addons`, which is deprecated. Also, this didn't seem to be rendering correctly with `fixed-data-table@0.6.0`. Didn't have time to investigate to much, but will take a look when I get a chance.

**Comment by vaiRk** [comment]
@jonjaques thanks for letting me know. I'll take a look as well

**Comment by vaiRk** [comment]
I haven't had much time lately, I'll try to get it done by monday along with the upgrade to ES6 (#6).

**Comment by jonjaques** [comment]
Sorry, nor have I - I'm not actively waiting for this or anything though so don't rush for me :)

**Comment by Amnesthesia** [comment]
+1 on this :)

**Comment by vaiRk** [comment]
Hey guys, sorry I haven't had time to look into this.

I said I'd push this a lot of mondays ago, I'm actually working on it for real now so a new version will be released by the end of the week. Source files will be ES6 as well in case anyone is interested on using ES6 modules for their app (plus switch to lodash for util functions which also provides an ES6 build).

Pull requests are always welcome. I'm not using this module any more so I'd be nice to get someone on board who actually has a use case for it, even though, I'll commit to migrate it to the new react + fixed-data-table versions.

Cheers

**Comment by vaiRk** [comment]
v2.0.0 is out!
