### ISSUE TITLE
Only width/height

### ISSUE THREAD

**Issue by jdelafon** [vaiRk/responsive-fixed-data-table#8]
Sometimes one wants to have a table responsive to the parent container's width or height, but not both. Also sometimes one wants to use Bootstrap 3 columns (grid system), which always have zero height whatever you write in your css. In both use cases you cannot use this module as it overrides any constant value you'd pass for width or height.

I would love to have it possibly responsive only in one dimension.

**Comment by vaiRk** [comment]
The table will adapt to whatever dimensions the parent has. If the parent has a fixed height that's as far as it will go.
